### ISSUE TITLE
Hard coded file paths hindering usage

### ISSUE THREAD

**Issue by JosephLalli** [maojanlin/biastools#7]
Hi there,

It's difficult to find tools to measure reference bias, so I'm very grateful for your work!

I'm having trouble using biastools, however.

I have vcf files produced from real datasets aligned to different reference genomes using different tools. When I try to follow the "real reads" section of your readme, I run this command:
`biastools --analyze -o biastools_testing -g /dev/shm/chm13v2.0_maskedY_rCRS.fasta -v mysample.t2t.bwamem.bcf -s mysample -r mysample_t2t_gatk -R`

I get the following error:

[E::hts_open_format] Failed to open file "biastools_testing/mysample.mysample_t2t_gatk.sorted.het.bam" : No such file or directory

I think that biastools is assuming that I am running analyze as part of the larger biastools pipeline of simulation/testing/etc.

Am I using this wrong? My goal is to get a measure of AD/(RD+AD) for different indel lengths, taking into account the nuances of indel alignment and minimum base qualities.

Thanks,
Joe

**Comment by maojanlin** [comment]
Hi @JosephLalli , thanks for pointing this issue out.  I've updated the biastools on both github and pypi, now you should be able to run the program with the command:
```
biastools --analyze -o biastools_testing -g /dev/shm/chm13v2.0_maskedY_rCRS.fasta -v mysample.t2t.bwamem.bcf \
                -s mysample -r mysample_t2t_gatk -R --bam path_to_bam
```
where the `path_to_bam` is the path to your BAM file containing reads mapping to chm13v2.0.

In addition, I am about to release a new version of biastools in the near future.  The run time complexity and interface will be improved.  Thank you.

**Comment by JosephLalli** [comment]
Thank you! I closed the issue because I thought I was trying to use the tool in a manner it wasn't intended for, but I'm glad to see I was wrong. 

Looking forward to the updated release!
-Joe
